#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap -layout us,ro -variant ,std -option grp:alt_shift_toggle
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5

bspc config border_width	3
bspc config window_gap		30
bspc config top_padding		30
bspc config split_ratio		0.5

bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	true

#bspc config normal_border_color		\#a1a0ad
bspc config normal_border_color		\#707070
#bspc config focused_border_color		\#545175
bspc config focused_border_color	\#383838

bspc rule -a Xfce4-terminal state=pseudo_tiled
bspc rule -a Thunar state=pseudo_tiled rectangle=802x530+0+0
bspc rule -a firefox:Navigator state=tiled rectangle=1440x810+0+0
bspc rule -a firefox:Firefox state=floating rectangle=200x200+0+0 center=on
bspc rule -a firefox:Browser state=floating
bspc rule -a firefox -o desktop='^2'
bspc rule -a Deluge-gtk state=pseudo_tiled rectangle=1280x720+0+0
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=tiled
bspc rule -a Parole state=tiled rectangle=800x540+0+0
bspc rule -a Eog state=floating
bspc rule -a Wrapper-2.0 state=floating border=off
bspc rule -a Pavucontrol state=floating rectangle=500x500+0+0 center=on
bspc rule -a Xfce4-panel state=floating border=on
bspc rule -a Blueman-manager state=floating rectangle=500x500+0+0 center=on

$HOME/.fehbg
pgrep -x xcompmgr > /dev/null || xcompmgr -c -C &
#$HOME/.config/polybar/launch.sh
pgprep -x xfce4-panel > /dev/null || xfce4-panel --disable-wm-check &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x blueman-applet > /dev/null || blueman-applet &
#pgrep -x xfce4-power-man > /dev/null || xfce4-power-manager &
#pgrep -x picom > /dev/null && pkill picom ; sleep 1; picom -D 0 --no-fading-openclose &
#pgrep -x plank > /dev/null || plank &
redshift -PO 5000
